from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _xml(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def generate_vector_card(run_dir: Path, *, scene_id: str, title: str, body: str, aspect_ratio: str = "9:16") -> dict[str, Any]:
    artifact_dir = run_dir / "artifacts"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    width, height = (1080, 1920) if aspect_ratio == "9:16" else (1280, 720)
    safe_title = _xml(title or "VideoForge Director")
    safe_body = _xml((body or "Generated by local vector_card plugin")[:72])
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <rect width="100%" height="100%" fill="#1a1814"/>
  <rect x="{width * 0.08:.0f}" y="{height * 0.12:.0f}" width="{width * 0.84:.0f}" height="{height * 0.76:.0f}" rx="28" fill="#2a241d" stroke="#b8956a" stroke-width="4"/>
  <text x="{width / 2:.0f}" y="{height * 0.38:.0f}" text-anchor="middle" fill="#f5f0e8" font-family="Georgia, serif" font-size="72">{safe_title}</text>
  <text x="{width / 2:.0f}" y="{height * 0.50:.0f}" text-anchor="middle" fill="#b8956a" font-family="Georgia, serif" font-size="38">{safe_body}</text>
  <text x="{width / 2:.0f}" y="{height * 0.72:.0f}" text-anchor="middle" fill="#7a6e5a" font-family="Arial, sans-serif" font-size="28">scene: {scene_id}</text>
</svg>
'''
    path = artifact_dir / f"{scene_id}_vector_card.svg"
    path.write_text(svg, encoding="utf-8", newline="\n")
    metadata = {
        "artifactId": f"artifact_{scene_id}_vector_card",
        "artifactType": "image",
        "sceneId": scene_id,
        "path": str(path),
        "mimeType": "image/svg+xml",
        "source": {"plugin": "vector_card", "version": "0.1.0", "network": False, "paid": False},
    }
    (artifact_dir / f"{scene_id}_vector_card.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return metadata


def create_delivery_artifacts(run_dir: Path, run_id: str) -> dict[str, Any]:
    artifact_dir = run_dir / "artifacts"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    preview = artifact_dir / "preview-manifest.json"
    preview.write_text(json.dumps({"runId": run_id, "status": "preview_ready"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    draft = artifact_dir / "jianying-draft"
    draft.mkdir(exist_ok=True)
    (draft / "draft_meta_info.json").write_text(json.dumps({"runId": run_id, "draft": "Pi Director candidate"}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {
        "preview": {"artifactId": "preview_manifest", "artifactType": "preview", "path": str(preview)},
        "jianying": {"artifactId": "jianying_draft", "artifactType": "jianying", "path": str(draft)},
    }
