import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, CheckCircle, Gear, ImageSquare, Play, Spinner } from '@phosphor-icons/react'
import { api } from '../lib/api'

type SceneRow = { id: string; text: string; prompt: string; negativePrompt: string; enabled: boolean }
const providerBlank = { enabled: false, providerId: 'openai-compatible', baseUrl: '', apiKey: '', model: '', timeoutSeconds: 120, maxConcurrency: 4 }

export default function ImageStudio() {
  const navigate = useNavigate()
  const [projects, setProjects] = useState<any[]>([]); const [projectId, setProjectId] = useState(''); const [scenes, setScenes] = useState<SceneRow[]>([])
  const [provider, setProvider] = useState<any>(providerBlank); const [models, setModels] = useState<any[]>([])
  const [size, setSize] = useState('1024x1024'); const [candidateCount, setCandidateCount] = useState(1); const [batch, setBatch] = useState<any>(null); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState('')
  const selectedCount = scenes.filter(scene => scene.enabled && scene.prompt.trim()).length
  const selectedCandidates = useMemo(() => {
    const map: Record<string, string> = {}; for (const item of batch?.items || []) { const row = item.candidates?.find((candidate: any) => candidate.status === 'selected') || item.candidates?.[0]; if (row) map[item.sceneId] = row.id } return map
  }, [batch])
  useEffect(() => { api.listProjects().then(setProjects).catch(() => setNotice('项目列表加载失败')); api.getAIImageProviderSettings().then(setProvider).catch(() => setNotice('生图服务设置读取失败')) }, [])
  useEffect(() => { if (!projectId) return; api.getProject(projectId).then(project => {
    const subtitleById = Object.fromEntries((project.subtitles || []).map((row: any) => [row.id, row])); const rows = project.structuredContent?.episode?.visualPlan?.scenes || []
    setScenes(rows.map((scene: any) => ({ id: scene.id, text: (scene.subtitleIds || []).map((id: string) => subtitleById[id]?.text || '').join(''), prompt: scene.prompt || scene.summary || '', negativePrompt: scene.negativePrompt || '', enabled: true })))
  }).catch(() => setNotice('此项目尚未建立 VisualPlan')) }, [projectId])
  const saveProvider = async () => { setBusy('save'); try { const saved = await api.saveAIImageProviderSettings(provider); setProvider({ ...provider, ...saved, apiKey: '' }); setNotice('生图服务设置已保存') } catch (error: any) { setNotice(error.message || '设置保存失败') } finally { setBusy('') } }
  const probe = async () => { setBusy('models'); try { const result = await api.fetchAIImageProviderModels(provider); setModels(result.models || []); setNotice(result.message || (result.ok ? '连接已验证' : '连接失败')) } catch (error: any) { setNotice(error.message || '连接测试失败') } finally { setBusy('') } }
  const generate = async () => { if (!projectId || !selectedCount) return; setBusy('generate'); try { const result = await api.startAIImageBatch(projectId, { model: provider.model, size, candidateCount, items: scenes.filter(scene => scene.enabled && scene.prompt.trim()).map(scene => ({ sceneId: scene.id, prompt: scene.prompt, negativePrompt: scene.negativePrompt })) }); setBatch(result.batch); setNotice(`已提交 ${selectedCount} 个场景，正在并行生成`); pollBatch(projectId, result.batchId, result.job.jobId) } catch (error: any) { setNotice(error.message || '批次创建失败') } finally { setBusy('') } }
  const pollBatch = async (pid: string, batchId: string, jobId: string) => { const tick = async () => { try { const [job, value] = await Promise.all([api.getJob(jobId), api.getAIImageBatch(pid, batchId)]); setBatch(value); if (job.status === 'queued' || job.status === 'running') window.setTimeout(tick, 900); else setNotice(job.status === 'succeeded' ? '图片候选已生成，请选择并批准' : (job.error || '生成失败')) } catch (error: any) { setNotice(error.message || '读取批次失败') } }; tick() }
  const choose = (sceneId: string, candidateId: string) => setBatch((current: any) => ({ ...current, items: current.items.map((item: any) => item.sceneId === sceneId ? { ...item, candidates: item.candidates.map((candidate: any) => ({ ...candidate, status: candidate.id === candidateId ? 'selected' : 'pending' })) } : item) }))
  const approve = async () => { if (!batch || !projectId) return; setBusy('approve'); try { const selections = Object.entries(selectedCandidates).map(([sceneId, candidateId]) => ({ sceneId, candidateId })); const result = await api.approveAIImageBatch(projectId, batch.batchId, selections); setBatch(result.batch); setNotice(`已绑定 ${result.bound.length} 个 Scene，可返回编辑器生成 Preview`) } catch (error: any) { setNotice(error.message || '批准绑定失败') } finally { setBusy('') } }
  return <main className="min-h-[100dvh] workbench-shell p-4 md:p-6"><div className="max-w-[1440px] mx-auto space-y-4">
    <header className="flex flex-wrap items-center gap-3"><button className="icon-button" onClick={() => navigate('/')} title="返回"><ArrowLeft size={18}/></button><div className="flex-1"><p className="section-index">IMAGE STUDIO / SCENE BATCH</p><h1 className="text-2xl font-heading">AI 生图工作台</h1></div><button className="btn-cinematic text-xs" onClick={() => navigate('/settings/agent')}><Gear size={15}/> Agent 设置</button></header>
    {notice && <div className="text-xs px-3 py-2 border" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface)' }}>{notice}</div>}
    <section className="grid lg:grid-cols-[300px_minmax(0,1fr)_300px] gap-4">
      <aside className="card-cinematic p-4 space-y-3"><h2 className="label-cinematic">项目与队列</h2><label className="text-xs">项目<select className="input-cinematic mt-1 w-full" value={projectId} onChange={event => { setProjectId(event.target.value); setBatch(null) }}><option value="">选择已有项目</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="text-xs" style={{ color: 'var(--text-muted)' }}>已选择 {selectedCount} / {scenes.length} 个 Scene</div><div className="space-y-2 max-h-[58vh] overflow-y-auto">{scenes.map(scene => <label key={scene.id} className="block p-2 border text-xs" style={{ borderColor: 'var(--border-subtle)', background: scene.enabled ? 'var(--bg-surface)' : 'transparent' }}><input type="checkbox" className="mr-2" checked={scene.enabled} onChange={event => setScenes(rows => rows.map(row => row.id === scene.id ? { ...row, enabled: event.target.checked } : row))}/><b>{scene.id}</b><span className="block mt-1 line-clamp-2" style={{ color: 'var(--text-muted)' }}>{scene.text || '无字幕文本'}</span></label>)}</div></aside>
      <section className="card-cinematic p-4 space-y-4 min-w-0"><div className="flex items-center justify-between"><h2 className="label-cinematic">场景候选</h2>{batch && <span className="status-pill" data-tone={batch.status === 'succeeded' ? 'ok' : 'warn'}>{batch.status}</span>}</div>{!batch && <div className="space-y-3">{scenes.filter(scene => scene.enabled).map(scene => <div key={scene.id} className="border p-3 space-y-2" style={{ borderColor: 'var(--border-subtle)' }}><div className="text-xs font-semibold">{scene.id}</div><textarea className="input-cinematic w-full min-h-[76px] text-sm" value={scene.prompt} placeholder="输入图片提示词" onChange={event => setScenes(rows => rows.map(row => row.id === scene.id ? { ...row, prompt: event.target.value } : row))}/><input className="input-cinematic w-full text-xs" value={scene.negativePrompt} placeholder="负面提示词（可选）" onChange={event => setScenes(rows => rows.map(row => row.id === scene.id ? { ...row, negativePrompt: event.target.value } : row))}/></div>)}{projectId && <button className="btn-gold w-full py-2 text-xs" disabled={!!busy || !selectedCount} onClick={generate}>{busy === 'generate' ? <Spinner size={15} className="animate-spin"/> : <Play size={15} weight="fill"/>} 并行生成 {selectedCount} 个 Scene</button>}</div>}{batch && <div className="space-y-4">{batch.items.map((item: any) => <div key={item.sceneId} className="border p-3 space-y-2" style={{ borderColor: 'var(--border-subtle)' }}><div className="flex justify-between text-xs"><b>{item.sceneId}</b><span style={{ color: item.status === 'failed' ? 'var(--danger)' : 'var(--text-muted)' }}>{item.status}{item.error ? ` · ${item.error}` : ''}</span></div><p className="text-xs line-clamp-2" style={{ color: 'var(--text-muted)' }}>{item.prompt}</p><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{item.candidates?.map((candidate: any) => <button key={candidate.id} className="relative border p-1" style={{ borderColor: selectedCandidates[item.sceneId] === candidate.id ? 'var(--accent)' : 'var(--border-subtle)' }} onClick={() => choose(item.sceneId, candidate.id)}><img className="w-full aspect-square object-cover" src={`/api/projects/${projectId}/assets/stream?path=${encodeURIComponent(candidate.path)}`} /><span className="text-[10px]">{selectedCandidates[item.sceneId] === candidate.id ? '已选择' : '候选'}</span></button>)}</div></div>)}<button className="btn-gold w-full py-2 text-xs" disabled={!!busy || !Object.keys(selectedCandidates).length} onClick={approve}>{busy === 'approve' ? <Spinner size={15} className="animate-spin"/> : <CheckCircle size={15} weight="fill"/>} 批准并绑定已选图片</button></div>}</section>
      <aside className="card-cinematic p-4 space-y-3"><h2 className="label-cinematic">生图服务</h2><label className="text-xs flex items-center gap-2"><input type="checkbox" checked={!!provider.enabled} onChange={event => setProvider({ ...provider, enabled: event.target.checked })}/> 启用 Provider</label><label className="text-xs">Base URL<input className="input-cinematic mt-1 w-full" value={provider.baseUrl} onChange={event => setProvider({ ...provider, baseUrl: event.target.value })} placeholder="https://gateway.example/v1"/></label><label className="text-xs">API Key<input className="input-cinematic mt-1 w-full" type="password" value={provider.apiKey} onChange={event => setProvider({ ...provider, apiKey: event.target.value })} placeholder={provider.apiKeyConfigured ? '已保存，留空保持不变' : 'sk-...'}/></label><label className="text-xs">模型<input className="input-cinematic mt-1 w-full" list="image-models" value={provider.model} onChange={event => setProvider({ ...provider, model: event.target.value })}/><datalist id="image-models">{models.map(model => <option key={model.id} value={model.id}/>)}</datalist></label><label className="text-xs">并发数<input className="input-cinematic mt-1 w-full" type="number" min="1" max="8" value={provider.maxConcurrency} onChange={event => setProvider({ ...provider, maxConcurrency: Number(event.target.value) })}/></label><label className="text-xs">尺寸<select className="input-cinematic mt-1 w-full" value={size} onChange={event => setSize(event.target.value)}><option>1024x1024</option><option>1024x1536</option><option>1536x1024</option></select></label><label className="text-xs">每 Scene 候选<select className="input-cinematic mt-1 w-full" value={candidateCount} onChange={event => setCandidateCount(Number(event.target.value))}><option value="1">1</option><option value="2">2</option><option value="4">4</option></select></label><div className="flex gap-2"><button className="btn-cinematic text-xs flex-1" disabled={!!busy || !provider.baseUrl} onClick={probe}>{busy === 'models' ? '连接中' : '测试并拉取模型'}</button><button className="btn-gold text-xs flex-1" disabled={!!busy} onClick={saveProvider}>{busy === 'save' ? '保存中' : '保存'}</button></div><div className="text-[10px]" style={{ color: 'var(--text-muted)' }}><ImageSquare size={13} className="inline mr-1"/>兼容 OpenAI 图片接口：`/models` 与 `/images/generations`</div></aside>
    </section>
  </div></main>
}
